---
- name: download Payara
  get_url:
    url: http://bit.ly/1Gm0GIw
    dest: "{{ dest_folder }}"

- name: unzip Payara
  shell: 'cd {{ {{ dest_folder }} }} && unzip {{ dest_folder }}/payara-4.1.1.154.zip'

- name: remove zip
  file:
    path: "{{ dest_folder }}/payara-4.1.1.154.zip"
    state: absent
