---
- name: download IntelliJ
  get_url:
    url: https://download.jetbrains.com/idea/ideaIU-2016.2.5.tar.gz
    dest: "{{ dest_folder }}"

- name: unzip IntelliJ
  unarchive:
    src: "{{ dest_folder }}/ideaIU-2016.2.5.tar.gz"
    dest: "{{ dest_folder }}"

- name: delete tar
  file:
    path: "{{ dest_folder }}/ideaIU-2016.2.5.tar.gz"
    state: absent
