---
- name: update apt cache
  apt:
    update_cache: yes

- name: add certificates
  apt:
    name: '{{ item }}'
    state: present
  with_items: 
  - ca-certificates
  - apt-transport-https

- name: adding apt key for docker repo
  command: 'apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D'

- name: add docker apt repo
  apt_repository:
    repo: '{{ item }}'
    state: present
  with_items:
  - deb https://apt.dockerproject.org/repo ubuntu-xenial main

- name: update apt cache
  apt:
    update_cache: yes

- name: install linux-image-extra
  apt: 
    name: '{{ item }}'
    state: present
  with_items:
  - linux-image-extra-{{ ansible_kernel }}
  - linux-image-extra-virtual

- name: install docker
  apt:
    name: docker-engine
    state: present
  notify: restart docker
