---
- hosts: basicSetUp

  vars_prompt:
    - name: "sudo_password"
      prompt: "Enter sudo password"
      private: yes

  become: yes

  vars:
    ansible_sudo_pass: '{{ sudo_password }}'

  roles:
    - docker
    - vim 
    - docker_compose
    - jdk
    - maven

- hosts: basicSetUp

  vars:
    dest_dir: '/home/{{ ansible_user }}/Desktop'

  roles:
    - role: intellij
      dest_folder: '{{ dest_dir }}'

    - role: payara
      dest_folder: '{{ dest_dir }}'
